# Generated by Django 4.1.3 on 2022-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipes',
        ),
    ]
